config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "commissions#index"
  resources :commissions, only:[:index, :new, :create, :show, :destroy] do
    member do
      get "select"
      get "selected_confirmation"
      patch "direct"
      get "unsuccessful"
      get "delete_confirmation"
    end
    collection do
      get "search"
    end
    resources :dealings, only:[:new, :create, :show, :destroy] do
      collection do
        get "make"
      end
    end
    resources :chats, only:[:create]
    resources :evaluations, only:[:new ,:create, :show]
  end

  resources :notifications, only:[:index, :destroy]
  
  resources :creators, only:[:index] do
    collection do
      get "search"
    end
  end
  resources :users, only:[:show, :edit, :update] do
    resources :achievements, only:[:new, :create ,:edit ,:update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :commissions
  has_many :notifications
  has_many :dealings
  has_one :achievement
  has_many :chats
  has_many :evaluations

  with_options presence: true do
    validates :user_name
    validates :name
    validates :reading_name, format: {with: /\A[ァ-ヴー]+\z/, message: "は全角カタカナで記入してください"}
    validates :postal_code, format: {with: /\A\d{3}-\d{4}\z/, message: "が正しくありません"}
    validates :prefectures, numericality: {other_than: 0}
    validates :city
    validates :kind, inclusion: [0,1]
  end

  with_options presence: true, if: :is_creator? do |user|
    user.validates :financial_institution
    user.validates :branch
    user.validates :deposit, numericality: {other_then: 0}
    user.validates :account_number, format: {with: /\A\d{4,7}\z/ , message: "は正しく入力してください"}
    user.validates :account_holder, format: {with: /\A[ァ-ヴー]+\z/, message: "は全角カタカナで記入してください"}
  end

  def self.search(user_name)
    if user_name != ""
      User.where("user_name LIKE(?)", "%#{user_name}%").where(kind: 1)
    else
      User.where(kind: 1)
    end
  end

  def is_creator?
    return kind == 1
  end
  #enum kind: {requester: 0, creator: 1}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @achievement = @user.achievement if @user.kind == 1
    
    if user_signed_in? && current_user.id == @user.id
      @commissions = Commission.where(user_id: @user.id).or(Commission.where(contractor_id: @user.id))
      @commissions_dealing = @commissions.where(status: Commission.statuses[:dealing])
      @commissions_finished = @commissions.where(status: Commission.statuses[:finished])
      @commissions_waiting = @commissions.where(status: Commission.statuses[:undealt])
      @commissions_unsuccessful = @commissions.where(status: Commission.statuses[:unsuccessful])
      @commissions_waiting_evaluation = @commissions.where(status: Commission.statuses[:waiting_evaluation])
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), flash: {user_update: "ユーザ情報を更新しました"}
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :email, :name, :reading_name, :postal_code, :prefectures, :city, :building_name, :kind, :financial_institution, :branch, :deposit, :account_number, :account_holder)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2 class="sub-title">ユーザ情報の編集</h2>

<div class="user-form-container">
  <%= form_with model: @user, local: true, class: "edit_user" do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <h3 class="form-title">ユーザ情報</h3>
    <div class="input-item">
      <%= f.label :user_name, "ユーザ名" %><span class="note">(必須)</span><br />
      <%= f.text_field :user_name, autofocus: true, autocomplete: "user_name", class: "input-user-text" %>
    </div>

    <div class="input-item">
      <%= f.label :email, "Eメール" %><span class="note">(必須)</span><br />
      <%= f.email_field :email, autocomplete: "email", class: "input-user-text" %>
    </div>

    <div class="input-item">
      <%= f.label :name, "氏名" %><span class="note">(必須)</span><br />
      <%= f.text_field :name, autocomplete: "name", class: "input-user-text" %>
    </div>

    <div class="input-item">
      <%= f.label :reading_name, "氏名（ヨミガナ）" %><span class="note">(必須)</span><br />
      <%= f.text_field :reading_name, autocomplete: "reading_name", class: "input-user-text" %>
    </div>

    <div class="input-item">
      <%= f.label :kind, "ユーザタイプ" %><br>
      <%= f.select(:kind, {"依頼者" => 0, "制作者" => 1}, {}, {class: "select-box"}) %>
    </div>

    <h3 class="form-title">住所</h3>
    <div class="input-item">
      <%= f.label :postal_code, "郵便番号" %><span class="note">(必須)</span><br>
      <%= f.text_field :postal_code, autocomplete: "postal_code", class: "input-user-text" %>
      <div class="note">郵便番号は123-4567の形式で入力してください</div>
    </div>

    <div class="input-item">
      <%= f.label :prefectures, "都道府県" %><span class="note">(必須)</span><br>
      <%= f.collection_select(:prefectures, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
    </div>

    <div class="input-item">
      <%= f.label :city, "市区町村" %><span class="note">(必須)</span><br>
      <%= f.text_field :city, autocomplete: "city", class: "input-user-text" %>
    </div>

    <div class="input-item">
      <%= f.label :building_name, "マンション・ビル名" %><br>
      <%= f.text_field :building_name, autocomplete: "buiding_name", class: "input-user-text" %>
    </div>

    <h3 class="form-title">口座情報</h3>
    <div class="form-description">
      <div class="note">以下は依頼を受ける予定の方のみ必須です</div>
    </div>
    <div class="input-item">
      <%= f.label :financial_institution, "金融機関名" %><br>
      <%= f.text_field :financial_institution, autocomplete: "financial_institution", class: "input-user-text" %>
    </div>

    <div class="input-item">
      <%= f.label :branch, "支店名" %><br>
      <%= f.text_field :branch, autocomplete: "branch", class: "input-user-text" %>
    </div>

    <div class="input-item">
      <%= f.label :deposit, "預金種目" %><br>
      <%= f.select(:deposit, {"---" => 0, "普通" => 1, "定期" => 2, "当座" => 3}, {}, {class:"select-box"}) %>
    </div>

    <div class="input-item">
      <%= f.label :account_number, "口座番号" %><br>
      <%= f.text_field :account_number, autocomplete: "account_number", class: "input-user-text" %>
    </div>

    <div class="input-item">
      <%= f.label :account_holder, "口座名義" %><br>
      <%= f.text_field :account_holder, autocomplete: "account_holder", class: "input-user-text" %>
    </div>

    <div class="actions">
      <%= f.submit "新規登録", class: "button-orange" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h2 class="sub-title"><%= @user.user_name %>さんのプロフィール</h2>

<div class="user-profile-container">
  <div class="user-profile">
    <div class="user-info-item">ユーザ名 : <%= @user.user_name %></div>
    <div class="user-info-item">現在ランク : <%= @user.rank %></div>
    <% if @user.kind == 1 %>
      <div class="profile-section">
        <h3 class="profile-headline"><%= @user.user_name %>さんの実績</h3>
        <% if @achievement %>
          <div class="user-info-item">今までに受けた依頼数 : <%= @achievement.commission_count %></div>
          <div class="user-info-item">
            <div class="user-sub-title">今までの実績</div>
            <div class="user-description"><%= @achievement.achievement_text %></diV>
          </div>
          <div class="user-info-item">
            <div class="user-sub-title">実績紹介</div>
            <div class="user-description"><%= @achievement.text %></diV>
          </div>
          <% if @achievement.images.attached? %>
            <div class="user-sub-title">画像</div>
            <div class="profile-images">
            <% @achievement.images.each do |image| %>
              <div class="profile-image"><%= image_tag image, class: "user-upload-image" %></div>
            <% end %>
            </div>
          <% end %>
          <% if user_signed_in? && current_user.id == @user.id %>
            <div class="achievement_link"><%= link_to "実績を編集する", edit_user_achievement_path(@user,@achievement) %></div>
          <% end %>
        <% else %>
          <div>まだ実績が設定されていません</div>
          <% if user_signed_in? && current_user.id == @user.id %>
            <div class="achievement_link"><%= link_to "実績を設定する", new_user_achievement_path(@user) %></div>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <% if user_signed_in? && current_user.id == @user.id %>
      <div class="profile-description">ここから下は御本人のみ表示されます。</div>
      <div class="profile-section">
        <h3 class="profile-headline">取引中の依頼</h3>
        <% if @commissions_dealing.present? %>
          <ul class="profile-commission-list">
          <% @commissions_dealing.each do |commission| %>
            <li><%= link_to commission.title, commission_dealing_path(commission,commission.dealing), class: "dealing-link" %></li>
          <% end %>
          </ul>
        <% else %>
          <div>現在取引中の依頼はありません。</div>
        <% end %>
      </div>
      <div class="profile-section">
        <h3 class="profile-headline">終了した取引</h3>
        <% if @commissions_finished.present? %>
          <ul class="profile-commission-list">
          <% @commissions_finished.each do |commission| %>
            <li class="profile-flex-item">
              <%= link_to commission.title, commission_dealing_path(commission,commission.dealing), class: "dealing-link dealing-link-adjustment" %>
              <% evaluation = commission.evaluations.find_by(target_user_id: current_user.id) %>
              <%= link_to "相手からの評価を見る", commission_evaluation_path(commission, evaluation), class: "dealing-link evaluation-link" %>
            </li>
          <% end %>
          </ul>
        <% else %>
          <div>完了した取引はありません。</div>
        <% end %>
      </div>
      <div class="profile-section">
        <h3 class="profile-headline">評価待ちの依頼</h3>
        <% if @commissions_waiting_evaluation.present? %>
          <ul class="profile-commission-list">
            <% @commissions_waiting_evaluation.each do |commission| %>
              <li class="profile-flex-item">
                <%= link_to commission.title, commission_dealing_path(commission,commission.dealing), class: "dealing-link dealing-link-adjustment" %>
                <% if !Evaluation.existence_evaluation?(current_user.id, commission.id) %>
                  <%= link_to "ユーザを評価する", new_commission_evaluation_path(commission), class: "dealing-link evaluation-link" %>
                <% else %>
                  <div class="waiting-evaluation-message">相手の評価待ち</div>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <div>評価待ちの依頼はありません。</div>
        <% end %>
      </div>
      <div class="profile-section">
        <h3 class="profile-headline">取引待ちの依頼</h3>
        <% if @commissions_waiting.present? %>
          <ul class="profile-commission-list">
            <% @commissions_waiting.each do |commission| %>
              <li><%= link_to commission.title, commission_path(commission), class: "dealing-link" %></li>
            <% end %>
          </ul>
        <% else %>
          <div>取引待ちの依頼はありません。</div>
        <% end %>
      </div>
      <div class="profile-section">
        <h3 class="profile-headline">不成立となった依頼</h3>
        <% if @commissions_unsuccessful.present? %>
          <ul class="profile-commission-list">
            <% @commissions_unsuccessful.each do |commission| %>
              <li><%= link_to commission.title, commission_path(commission), class: "dealing-link" %></li>
            <% end %>
          </ul>
        <% else %>
          <div>不成立となった依頼はありません。</div>
        <% end %>
      </div>
      <div class="profile-section">
        <h3 class="profile-headline">個人情報</h3>
        <div class="user-info-item">Eメール : <%= @user.email %></div>
        <div class="user-info-item">名前 : <%= @user.name %></div>
        <div class="user-info-item">名前（ヨミガナ） : <%= @user.reading_name %></div>
        <div class="user-info-item">郵便番号 : <%= @user.postal_code %></div>
        <div class="user-info-item">都道府県 : <%= Prefecture.data[@user.prefectures.to_i][:name] %></div>
        <div class="user-info-item">市区町村 : <%= @user.city %></div>
        <div class="user-info-item">マンション・建物名 : <%= @user.building_name %></div>
        <div class="user-info-item">金融機関名 : <%= @user.financial_institution %></div>
        <div class="user-info-item">支店名 : <%= @user.branch %></div>
        <% deposit = ["", "普通" ,"定期", "当座"] %>
        <div class="user-info-item">預金種目 : <%= deposit[@user.deposit.to_i] %></div>
        <div class="user-info-item">口座番号 : <%= @user.account_number %></div>
        <div class="user-info-item">口座名義 : <%= @user.account_holder %></div>
      </div>
      <%= link_to "ユーザ情報を編集する", edit_user_path(@user) %>
    <% end %>
  </div>
</div>

<div class="user-button-center">
  <%= link_to "戻る", :back, class: "button-gray" %>
</div>