config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "commissions#index"
  resources :commissions, only:[:index, :new, :create, :show, :destroy] do
    member do
      get "select"
      get "selected_confirmation"
      patch "direct"
      get "unsuccessful"
      get "delete_confirmation"
    end
    collection do
      get "search"
    end
    resources :dealings, only:[:new, :create, :show, :destroy] do
      collection do
        get "make"
      end
    end
    resources :chats, only:[:create]
    resources :evaluations, only:[:new ,:create, :show]
  end

  resources :notifications, only:[:index, :destroy]
  
  resources :creators, only:[:index] do
    collection do
      get "search"
    end
  end
  resources :users, only:[:show, :edit, :update] do
    resources :achievements, only:[:new, :create ,:edit ,:update]
  end
end

app/controllers/creators_controller.rb
class CreatorsController < ApplicationController
  def index
    user_id = user_signed_in? ? current_user.id : nil
    @creators = User.where(kind: 1).where.not(id: user_id)
  end

  def search
    @creators = User.search(params[:user_name])
  end
end

app/helpers/creators_helper.rb
module CreatorsHelper
end

app/views/creators/_creator.html.erb
<div class="create-item">
  <div class="create-name"><%= link_to creator.user_name, user_path(creator) %></div>
  <% if @commission %>
    <div class="commission-select">
      <%= link_to "このユーザに依頼する", selected_confirmation_commission_path(@commission, user_id: creator.id), class: "button-orange" %>
    </div>
  <% end %>
</div>

app/views/creators/_search_form.html.erb
<div class="request-search">
  <%= form_with url: search_creators_path, local: true, method: :get, class: "request-search-form" do |f| %>
    <div class="form-upper">
      <%= f.text_field :user_name, placeholder: "ここにユーザ名を入力", class: "search-input" %>
    </div>
    <div class="search-button-container">
      <%= f.submit value: "検索", class: "search-button" %>
    </div>
  <% end %>
</div>

app/views/creators/index.html.erb
<h2 class="sub-title">制作者一覧</h2>

<%= render partial: "search_form" %>

<div class="creators-list-container">
  <div class="creators-list">
    <%= render partial: "creator", collection: @creators %>
  </div>
</div>
<div class="user-button-center">
  <%= link_to "戻る", root_path, class: "button-gray" %>
</div>

app/views/creators/search.html.erb
<h2 class="sub-title">製作者の検索結果</h2>

<%= render partial: "search_form" %>
<div class="result-count"><%= @creators.count %>件の検索結果</div>

<div class="creators-list-container">
  <% if @creators.present? %>
    <div class="creators-list">
      <%= render partial: "creator", collection: @creators %>
    </div>    
  <% else %>
    <div class="message">検索結果はありません</div>
  <% end %>
</div>

<div class="user-button-center">
  <%= link_to "戻る", creators_path, class: "button-gray" %>
</div>