config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "commissions#index"
  resources :commissions, only:[:index, :new, :create, :show, :destroy] do
    member do
      get "select"
      get "selected_confirmation"
      patch "direct"
      get "unsuccessful"
      get "delete_confirmation"
    end
    collection do
      get "search"
    end
    resources :dealings, only:[:new, :create, :show, :destroy] do
      collection do
        get "make"
      end
    end
    resources :chats, only:[:create]
    resources :evaluations, only:[:new ,:create, :show]
  end

  resources :notifications, only:[:index, :destroy]
  
  resources :creators, only:[:index] do
    collection do
      get "search"
    end
  end
  resources :users, only:[:show, :edit, :update] do
    resources :achievements, only:[:new, :create ,:edit ,:update]
  end
end

app/models/commission.rb
class Commission < ApplicationRecord
  belongs_to :user
  has_one :notification, dependent: :destroy
  has_one :dealing
  has_many :evaluations

  DEADLINE_DAYS = 7

  with_options presence: true do
    validates :title
    validates :description
    validates :limit_date
    validates :reward, numericality: { in: 5000..1000000 }
  end
  validates :directly, inclusion: [true, false]
  validate :date_before_start

  def self.search(search, less, greater, limit_days)
    result = nil
    if search != ""
      result = Commission.where("title LIKE(?)", "%#{search}%").where(directly: false).where(status: Commission.statuses[:undealt])
    else
      result = Commission.where(directly: false).where(status: Commission.statuses[:undealt])
    end
    if (less != "" || greater != "")
      if less == ""
        result = result.where(reward: ..greater)
      elsif greater == ""
        result = result.where(reward: less..)
      else
        result = result.where(reward: less..greater)
      end
    end
    if limit_days != ""
      limit_date = Date.today + limit_days.to_i
      result = result.where(limit_date: ..limit_date)
    end
    return result
  end

  def partner_id(user_id)
    return user_id == self.user_id ? self.contractor_id : self.user_id
  end

  private
  def date_before_start
    return if limit_date.blank?
    errors.add(:limit_date, "は一週間以上先のものを選択してください") if limit_date < Date.today + DEADLINE_DAYS
  end

  enum status:{undealt: 0, dealing: 1, finished: 2, unsuccessful: 3, waiting_evaluation: 4}
end

app/controllers/commissions_controller.rb
class CommissionsController < ApplicationController
  before_action :direct_commission, only: [:show]
  before_action :redirect_root, only:[:select, :selected_confirmation, :direct, :delete_confirmation, :destroy]

  def index
    @commissions = Commission.where(directly: false).where(status: Commission.statuses[:undealt]).includes(:user)
    session[:return_to_page] = "トップページに戻る"
    session[:previous_url] = request.url
  end

  def new
    @commission = Commission.new
  end

  def create
    @commission = Commission.new(commission_param)
    if @commission.save
      if @commission.directly
        redirect_to select_commission_path(@commission)
      else
        redirect_to commission_path(@commission)
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def select
    @creators = User.where(kind: 1).where.not(id: current_user.id)
  end

  def selected_confirmation
    @creator = User.find(params[:user_id])
  end

  def direct
    creator = User.find(params[:user_id])
    @commission.contractor_id = creator.id
    @commission.save
    Notification.create(user_id: creator.id, commission_id: @commission.id)
    redirect_to commission_path(@commission), flash: {direcly: "#{creator.user_name}さんに依頼しました"}
  end

  def unsuccessful
    @commission = Commission.find(params[:id])
  end

  def search
    @keyword = params[:keyword]
    @commissions = Commission.search(@keyword, params[:reward_lower], params[:reward_upper], params[:limit_days]).includes(:user)
    @count = @commissions.count
  end

  def delete_confirmation
    @commission = Commission.find(params[:id])
  end

  def destroy
    commission = Commission.find(params[:id])
    commission.destroy
    redirect_to root_path, flash: {deleted: "依頼を削除しました"}
  end

  private
  def commission_param
    params.require(:commission).permit(:title, :description, :limit_date, :reward, :directly, :contractor).merge(user_id: current_user.id)
  end

  def direct_commission
    @commission = Commission.find(params[:id])
    if @commission.directly && (!user_signed_in? || @commission.contractor_id != current_user.id && @commission.user_id != current_user.id)
      redirect_to root_path
    end
  end

  def redirect_root
    @commission = Commission.find(params[:id])
    if !user_signed_in? || @commission.user_id != current_user.id
      redirect_to root_path
    end
  end
end

app/helpers/commissions_helper.rb
module CommissionsHelper
end

app/views/commissions/_commission.html.erb
<% days_left = (commission.limit_date - Date.today).to_i %>
<div class="commission-container">
  <div class="commission-content">
    <div class="commission-header">
      <div class="commission-title">
        <h3><%= commission.title %></h3>
      </div>
      <div class="user-name">
        <%= commission.user.user_name %>
      </div>
    </div>
    <div class="commission-description">
      <%= commission.description %>
    </div>
    <div class="commission-reward">
      <span class="information-item">報酬 : </span><span class="important"><%= commission.reward %>円</span>
    </div>
    <div class="limit-date">
      <span class="information-item">期限日 : </span><span class="important"><%= commission.limit_date %></span>
    </div>
    <% if days_left >= Commission::DEADLINE_DAYS %>
      <div class="days_left">
        <span class="information-item">残り日数 : </span><span class="important"><%= days_left %>日</span>
      </div>
    <% end %>
    <% if controller.controller_name == "commissions" && controller.action_name == "show" %>
      <% if days_left >= Commission::DEADLINE_DAYS %>
        <% if user_signed_in? && commission.user_id != current_user.id && current_user.kind == 1 %>
          <div class="commission-reception">
            <%= link_to "この依頼を受け付ける", new_commission_dealing_path(commission), class: "agreement" %>
            <% if commission.directly %>
              <%= link_to "断る", unsuccessful_commission_path(commission), class: "refuse" %>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <div class="deadline-has-passed">この依頼は期限日までが<%= Commission::DEADLINE_DAYS %>日を下回ったか、期限が過ぎてしまったので受けられません</diV>
      <% end %>
      <% if user_signed_in? && current_user.id == commission.user_id %>
        <div class="user-button-center">
          <%= link_to "削除する", delete_confirmation_commission_path(@commission), class: "button-orange" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/commissions/_commissions_item.html.erb
<% days_left = (commission.limit_date - Date.today).to_i %>
<div class="request-item">
  <div class="request-item-left">
    <div class="request-item-upper">
      <div class="request-title">
        <%= link_to commission.title, commission_path(commission) %>
      </div>
    </div>
    <div class="request-item-lower">
      <div class="user-name">
        <%= commission.user.user_name %>
      </div>
    </div>
  </div>
  <div class="request-right">
    <div class="reqard">
      <span class="reward-item-name">報酬</span> : <span class="reward-price"><%= commission.reward %>円</span>
    </div>
    <% if days_left >= Commission::DEADLINE_DAYS %>
      <div class="days-left">
        残り日数 : <span class="days-left-num"><%= days_left %>日</span>
      </div>
    <% end %>
  </div>
</div>

app/views/commissions/_search_from.html.erb
<div class="request-search">
    <%= form_with url: search_commissions_path, local: true, method: :get, class: "request-search-form" do |f| %>
      <div class="form-upper">
        <%= f.text_field :keyword, placeholder: "ここにキーワードを入力", class: "search-input" %>
      </div>
      <div class="form-lower">
        <div class="search-input-item">
          <%= f.label :reward, "報酬で絞り込み" %>
          <%= f.text_field :reward_lower, placeholder: "下限", class: "input-number" %>
          〜
          <%= f.text_field :reward_upper, placeholder: "上限", class: "input-number" %>
        </div>
        <div class="search-input-item">
          <%= f.label :limit_days, "残り応募日数" %>
          <%= f.text_field :limit_days, class: "input-number" %>
        </div>
      </div>
      <div class="search-button-container">
        <%= f.submit value: "検索", class: "search-button" %>
      </div>
    <% end %>
  </div>

app/views/commissions/delete_confirmation.html.erb
<h2 class="sub-title">依頼の削除</h2>

<% if @commission.undealt? || @commission.unsuccessful? %>
  <div class="confirmation">以下の依頼を削除しますか？</div>
  <div class="page-description">削除した依頼は元に戻せません。</div>
<% else %>
  <div class="confirmation">以下の依頼は現在取引中か終了している為、削除ができません。</div>
<% end %>
<%= render partial: "commissions/commission", locals: {commission: @commission} %>

<% if @commission.undealt? || @commission.unsuccessful? %>
  <div class="select-button">
    <%= link_to "はい", commission_path(@commission), data:{turbo_method: :delete}, class: "button-orange" %>
    <%= link_to "いいえ", commission_path(@commission), class: "button-gray" %>
  </div>
<% else %>
  <div class="user-button-center">
    <%= link_to "戻る", :back, class: "button-gray" %>
  </div>
<% end %>

app/views/commissions/index.html.erb
<div class="site-description">
  <div class="site-description-opacity">
    <div class="highlight">思い出を手に取って見てみませんか。</div>
    <div class="site-sentence">あなたの思い出を立体として蘇らせます。</div>
  </div>
</div>
<div class="request-container">
  <div class="request-index-title">
    <h2>依頼一覧</h2>
  </div>
  <%= render partial: "search_from" %>
  <div class="creators-link">
    <div class="creators-button">
      <%= link_to "制作者一覧はこちら", creators_path %>
    </div>
  </div>
  <div class="requests">
    <div class="request-list">
      <%= render partial: "commissions_item", collection: @commissions, as: "commission" %>
    </div>
  </div>
</div>

app/views/commissions/new.html.erb
<h2 class="sub-title">依頼の作成</h2>

<div class="commissions-input-form">
  <%= form_with model: @commission ,local: true, class: "create-commission-form" do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class="input-item">
      <%= f.label :title, "依頼タイトル" %><span class="note">(必須)</span><br>
      <%= f.text_field :title, autofocus: true, class: "input-user-text" %>
    </div>
    <div class="input-item">
      <%= f.label :description, "説明文" %><span class="note">(必須)</span><br>
      <%= f.text_area :description, class: "input-text" %>
    </div>
    <div class="input-item">
      <%= f.label :limit_date, "期限日" %>
      <%= f.date_field :limit_date %><span class="note">(必須)</span>
      <div class="note">期限は今日より一週間以上先を指定してください</div>
    </div>
    <div class="input-item">
      <%= f.label :reward, "報酬（日本円）" %><span class="note">(必須)</span>
      <%= f.text_field :reward, class: "input-user-text" %>
      <div class="note">5,000円〜1,000,000円</div>
    </div>
    <div class="input-item">
      <%= f.radio_button :directly, :false %>
      <%= f.label :directly, "公開", {value: :false, style: "display: inline-block;"} %>
      <%= f.radio_button :directly, :true %>
      <%= f.label :directly, "直接依頼", {value: true, style: "display: inline-block;"} %>
    </div>
    <%= f.submit "作成", class: "button-orange" %>
  <% end %>
</div>
<div class="user-button-center">
  <%= link_to "戻る", root_path, class: "button-gray" %>
</div>

app/views/commissions/search.html.erb
<h2 class="sub-title"><%= @keyword != "" ? "\"#{@keyword}\"の" : "" %>検索結果</h2>

<div class="request-container">
  <%= render partial: "search_from" %>
  <div class="result-count"><%= @count %>件の検索結果</div>
  <div class="requests">
    <% if @commissions.present? %>
      <div class="request-list">
        <%= render partial: "commissions_item", collection: @commissions, as: "commission" %>
      </div>
    <% else %>
      <div class="message">検索結果はありません</div>
    <% end %>
  </div>
</div>

<div class="user-button-center">
  <%= link_to "戻る", root_path, class: "button-gray" %>
</div>

app/views/commissions/select.html.erb
<h2 class="sub-title">制作者の選択</h2>

<%= render partial: "creators/search_form" %>

<div class="creators-list-container">
  <div class="creators-list">
    <%= render partial: "creators/creator", collection: @creators %>
  </div>
</div>

<div class="user-button-center">
  <%= link_to "戻る", new_commission_path, class: "button-gray" %>
</div>

app/views/commissions/selected_confirmation.html.erb
<h2 class="sub-title">確認</h2>
<div class="confirmation">以下のユーザでよろしいですか？</div>

<div class="page-description">直接依頼した場合、以下のユーザに通知されます。</div>

<div class="user-profile-container">
  <div class="user-profile">
    <div class="user-info-item">ユーザ名 : <%= @creator.user_name %></div>
    <div class="user-info-item">現在ランク : <%= @creator.rank %></div>
  </div>
</div>

<div class="select-button">
  <%= link_to "はい", direct_commission_path(@commission, user_id: @creator.id), data:{turbo_method: :patch}, class: "button-orange" %>
  <%= link_to "いいえ", select_commission_path(@commission), class: "button-gray" %>
</div>

app/views/commissions/show.html.erb
<h2 class="sub-title">依頼詳細</h2>

<%= render partial: "commission", locals: {commission: @commission} %>

<div class="user-button-center">
  <%= link_to session[:return_to_page], session[:previous_url], class: "button-gray" %>
</div>

app/views/commissions/unsuccessful.html.erb
<h2 class="sub-title">断る依頼の確認</h2>
<div class="confirmation">以下の依頼を断りますか？</div>

<%= render partial: "commissions/commission", locals: {commission: @commission} %>

<div class="select-button">
  <%= link_to "はい", notification_path(@commission.notification.id), data:{turbo_method: :delete}, class: "button-orange" %>
  <%= link_to "いいえ", commission_path(@commission), class: "button-gray" %>
</div>