config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "commissions#index"
  resources :commissions, only:[:index, :new, :create, :show, :destroy] do
    member do
      get "select"
      get "selected_confirmation"
      patch "direct"
      get "unsuccessful"
      get "delete_confirmation"
    end
    collection do
      get "search"
    end
    resources :dealings, only:[:new, :create, :show, :destroy] do
      collection do
        get "make"
      end
    end
    resources :chats, only:[:create]
    resources :evaluations, only:[:new ,:create, :show]
  end

  resources :notifications, only:[:index, :destroy]
  
  resources :creators, only:[:index] do
    collection do
      get "search"
    end
  end
  resources :users, only:[:show, :edit, :update] do
    resources :achievements, only:[:new, :create ,:edit ,:update]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoDiorama</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= include_gon %>
  </head>

  <body>
    <header class="site-header">
      <%= link_to image_tag("site-logo_kari.png", class: "site-logo"), root_path %>
      <div class="header-right">
        <% if user_signed_in? %>
          <diV class="user-menu">
            <% if @notification_count > 0 %>
              <div class="notification-icon">!</div>
            <% end %>
            <div class="header-user-name"><%= current_user.user_name %></div>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", user_path(current_user) %></li>
              <% if @notification_count > 0 %>
                <li><%= link_to "依頼が届いています！", notifications_path, class: "notification" %></li>
              <% end %>
              <li><%= link_to "ログアウト", destroy_user_session_path, data:{turbo_method: :delete} %></li>
            </ul>
          </div>
          <%= link_to "依頼する", new_commission_path, class: "header-button" %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "header-button" %>
          <%= link_to "新規登録", new_user_registration_path, class: "header-button" %>
        <% end %>
      </div>
    </header>
    <% flash.each do |message_type, message| %>
      <div class="flash-messages"><%= message %></div>
    <% end %>
    <div class="site-main-container">
      <%= yield %>
    </div>
    <footer class="site-footer">
      Photo Diorama - 2023
    </footer>
  </body>
</html>